### ISSUE TITLE
Problems running the project

### ISSUE THREAD

**Issue by ghost** [mongodb-labs/socialite#18]
Got this trace and cant make sense out of it:

INFO  [2024-03-08 18:14:03,274] com.mongodb.socialite.ServiceManager: Initializing configured services
INFO  [2024-03-08 18:14:03,335] org.reflections.Reflections: Reflections took 50 ms to scan 1 urls, producing 41 keys and 90 values 
Exception in thread "main" FAILED_TO_LOAD_SERVICE
	serviceName : DefaultUserService
	ServiceClass : DefaultUserService
	at com.mongodb.socialite.ServiceFactory.getServiceImplByName(ServiceFactory.java:204)
	at com.mongodb.socialite.ServiceFactory.createService(ServiceFactory.java:71)
	at com.mongodb.socialite.ServiceFactory.createAndRegisterService(ServiceFactory.java:51)
	at com.mongodb.socialite.ServiceManager.<init>(ServiceManager.java:58)
	at com.mongodb.socialite.SocialiteService.run(SocialiteService.java:40)
	at com.mongodb.socialite.SocialiteService.run(SocialiteService.java:12)
	at com.yammer.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:38)
	at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:58)
	at com.yammer.dropwizard.cli.Cli.run(Cli.java:53)
	at com.yammer.dropwizard.Service.run(Service.java:61)
	at com.mongodb.socialite.SocialiteService.main(SocialiteService.java:20)

**Comment by ghost** [comment]
Solved
